# This file is the template of dfget configuration file.
# You can configure your dfget by change the parameter according your requirement.

# Nodes specify supernodes.
# Where the host is necessary, the port(default: 8002) and the weight(default:1) are optional.
---
nodes:
   - 127.0.0.1=1
   - 10.10.10.1:8002=2

# LocalLimit rate limit about a single download task, format: G(B)/g/M(B)/m/K(B)/k/B
# pure number will also be parsed as Byte.
localLimit: 20M

# Minimal rate about a single download task, format: G(B)/g/M(B)/m/K(B)/k/B
# pure number will also be parsed as Byte.
minRate: 64KB

# TotalLimit rate limit about the whole host includes download and upload, format: G(B)/g/M(B)/m/K(B)/k/B
# pure number will also be parsed as Byte.
#
# Suppose that there are two tasks on the same host
#  and the `localLimit` for each task is 20MB.
#  The actual download speed limit for each task will be 10MB when the `totalLimit` is 20MB.
# totalLimit: 20M

# ClientQueueSize is the size of client queue
# which controls the number of pieces that can be processed simultaneously.
# It is only useful when the Pattern equals "source".
# The default value is 6.
clientQueueSize: 6
